name: CI-CD

on:
  push:
    branches: [ main, develop, release/** ]
  pull_request:
    branches: [ main, develop, release/** ]
  workflow_dispatch:
   inputs:
      input:
        description: "Execute CI/CD"
        required: false
        default: "Execute CI/CD manually"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: |
        dotnet restore Ambev.DeveloperEvaluation.sln
     
    - name: Build
      run: |
        dotnet build Ambev.DeveloperEvaluation.sln --no-restore
        
    - name: Unit Test
      run: |
        dotnet test Ambev.DeveloperEvaluation.sln --no-build --logger:"html;LogFileName=resultado-testes.html" --collect:"XPlat Code Coverage"